### PR TITLE
Unifying the use of environmental variables.

### PR DESCRIPTION
**Pull request by tharna**
Add `ENVIRONMENT_NAME` environment variable to Lando to comply with Silta environments.

### CODE REVIEW

**Comment by tormi** [comment]
@tharna , we don't use this envvar in local ATM. Should we add environment's switch to the `settings.php` as well in the same go? We're using this ATM for local env:

```
if (getenv('LANDO_INFO') && file_exists($app_root . '/' . $site_path . '/settings.lando.php')) {
  include $app_root . '/' . $site_path . '/settings.lando.php';
}
```

**Comment by tharna** [comment]
While it's not used out of the box, there are many projects relying on it to define which environments they are running. Would be better to have one variable work for all environments than having another one affecting only local. Using this in the settings.php would therefore also make sense.

**Comment by tormi** [comment]
We've been using `WKV_SITE_ENV` previously for this, https://github.com/wunderio/WunderTools/blob/master/drupal/web/sites/default/settings.php#L52-L74. I can add `lando` / `local` implementation for `ENVIRONMENT_NAME`. What would be the other default environments needed here?

**Comment by tharna** [comment]
Yes, `ENVIRONMENT_NAME` basically replaced `WKV_SITE_ENV` in Silta. I've seen this implemented in various ways since, so some example would definitely be good. In Silta there should always be `master`, `production` and `local`/ `lando` + feature environments (`feature*`). Some projects also use `develop` in their workflow.

**Review by tormi — APPROVED** [review]
I have added related environment variables changes we agreed on Slack + resolved the related issue #170.

**Pull request merged**
