### PR TITLE
WIP: Use Drupal core Scaffold Composer plugin.

### PR DESCRIPTION
**Pull request by tormi**
## References

- CR: [Introduce Drupal Scaffold Composer plugin](https://www.drupal.org/node/3041017)
- Drupal Scaffold Files readme: https://git.drupalcode.org/project/drupal/blob/8.8.x/core/assets/scaffold/README.txt
- [DrupalEasy Podcast 221 - Greg Anderson - Composer Support in Drupal 8 Core Initiative](https://www.drupaleasy.com/podcast/2019/08/drupaleasy-podcast-221-greg-anderson-composer-support-drupal-8-core-initiative) 

This is basically a copy/paste from https://github.com/drupal-composer/drupal-project/pull/522, credit goes to @greg-1-anderson.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Caution: see https://www.drupal.org/project/drupal/issues/3086148

The name of the scaffold metadata key in the composer.json extra section might change this week. Friday is the code freeze, so whatever is in at that point will be stable.

**Comment by greg-1-anderson** [comment]
See https://github.com/drupal-composer/drupal-project/pull/522#issuecomment-539726950; all builds for Drupal 8.7.x and earlier will fail for a time.

**Comment by tormi** [comment]
Thanks, Greg!

**Comment by tormi** [comment]
See also:
- https://drupal.slack.com/archives/C392CHBEW/p1572524884468800
- https://drupal.slack.com/archives/C392CHBEW/p1572524891469100

**Comment by tormi** [comment]
The reason for f6a861e:

```
#!/bin/bash -eo pipefail
if [ -f phpcs.xml ] && [ -f vendor/bin/phpcs ]; then
  vendor/bin/phpcs --standard=phpcs.xml -s --colors
fi

FILE: /home/circleci/project/autoload.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 8 | ERROR | [x] Expected 1 space after asterisk; 0 found
   |       |     (Drupal.Commenting.DocCommentAlignment.NoSpaceAfterStar)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 2.58 secs; Memory: 12MB

Exited with code 2
```

**Comment by tormi** [comment]
Palantir's template maintainer's thread about the issue: https://drupal.slack.com/archives/C392CHBEW/p1572892152053100

**Comment by tormi** [comment]
- Avoid overwriting .htaccess changes during scaffolding, https://www.drupal.org/project/drupal/issues/3092563

**Comment by tormi** [comment]
Closing in favour of https://github.com/wunderio/drupal-project/pull/89.

**Pull request closed without merging**
