### PR TITLE
Upgrading the local Elasticsearch service to version 7.12, fixes #196.

### PR DESCRIPTION
**Pull request by tormi**
Fixes: https://github.com/wunderio/drupal-project/pull/196. Thanks, @vermario!

Note: you need the latest Lando (yes, pre-release), or at least [v3.1.0](https://github.com/lando/lando/releases/tag/v3.1.0) for ES 7.12. See also: https://github.com/wunderio/drupal-project/blob/master/.lando.yml#L103-L104.

Changes:

- Replace the custom `bitnami/elasticsearch` setup with the Lando Elasticsearch service. The slight disadvantage is that we can only use versions implemented in Lando.
- Currently, we have been **replacing** the built-in `elasticsearch.yml`. This PR introduces [**extending** the default configuration with custom settings](https://github.com/bitnami/bitnami-docker-elasticsearch#configuration-file) via `.lando/my_elasticsearch.yml` file, such as enabling CORS requests.
- Remove unnecessary defaults from the Kibana service, re-introduce a dedicated proxy address.
- Update the readme.

This setup creates the following `elasticsearch.yml` (with CORS enabled as an example):

```
http:
  port: 9200
  cors:
    enabled: true
    allow-origin: "*"
path:
  data: /bitnami/elasticsearch/data
transport:
  tcp:
    port: 9300
network:
  host: 172.26.0.3
  publish_host: 172.26.0.3
  bind_host: 0.0.0.0
cluster:
  name: bespin
node:
  name: lando
  master: true
  data: true
  ingest: false
discovery:
  type: single-node
plugin:
  mandatory: analysis-icu
```

Bitnami provides the following additional environment variables for Elasticsearch that can be used in this configuration: https://github.com/bitnami/bitnami-docker-elasticsearch#setting-up-a-cluster

### CODE REVIEW

**Comment by vermario** [comment]
hi! I wonder if I am doing something wrong, because after decommenting the elasticsearch part, I get this error if I do `lando start`:

```Let's get this party started! Starting app silta...
ERROR ==> elasticsearch version 7.12.0 is not supported message=elasticsearch version 7.12.0 is not supported, stack=Error: elasticsearch version 7.12.0 is not supported```

**Comment by tormi** [comment]
Sorry about that - you need the latest Lando (yes, prerelease), or at least [v3.1.0](https://github.com/lando/lando/releases/tag/v3.1.0).

See also: https://github.com/wunderio/drupal-project/blob/master/.lando.yml#L104

**Comment by tormi** [comment]
@pirog agreed that it's worth using `my_elasticearch.yml` setup in Lando ES service as well, https://github.com/lando/lando/issues/2992.

**Comment by tormi** [comment]
@vermario, of course you can use older supported ES versions in your project as well.

**Comment by vermario** [comment]
> Sorry about that - you need the latest Lando (yes, pre-release), or at least [v3.1.0](https://github.com/lando/lando/releases/tag/v3.1.0).
> 
> See also: https://github.com/wunderio/drupal-project/blob/master/.lando.yml#L104

ohh sorry I am in a bit of a hurry in current project, I don't dare updating to other lando versions at the moment :-)

**Pull request merged**
