### PR TITLE
WD-266: Replace local Mailhog service with Mailpit

### PR DESCRIPTION
**Pull request by tormi**
## Changes

- WD-266: Replace local Mailhog service with Mailpit

## Testing

Rebuild the project and try to send an email in local environment.

- http://mail.lndo.site
Screenshot 2024-09-27 at 13 57 19

### CODE REVIEW

**Review by ragnarkurmwunder — APPROVED** [review]

**Comment by tormi** [comment]
Minor unrelated `phpcs` issue:

```sh
FILE: ...b/modules/custom/phpunit_example/tests/src/Unit/AddClassTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | ERROR | [x] Use statements should be sorted alphabetically. The
   |       |     first wrong one is Drupal\Tests\UnitTestCase.
   |       |     (SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses.IncorrectlyOrderedUses)
```

**Comment by tormi** [comment]
> Minor unrelated phpcs issue:

This seems to be a false flag as use statements are sorted in correct order:

```php
<?php

namespace Drupal\Tests\phpunit_example\Unit;

use Drupal\phpunit_example\AddClass;
use Drupal\Tests\UnitTestCase;
```

**Comment by maijs** [comment]
1. Run the following commands within the PR branch:
```
lando start
lando drush si 
```
2. Opened https://drupal-project.lndo.site/user/password and entered `admin` as a username.
3. Opened https://mail.lndo.site but there were no emails received from Drupal.

Reverted back to `main`, and after completing these steps again, I did receive the email in the Mailhog interface.

**Comment by tormi** [comment]
You're correct, thanks! However, it works with SMTP module enabled. I'll investigate further.

**Comment by tormi** [comment]
@maijs, thank you once again for testing out!

I added the default Symfony Mailer configuration for the local Mailpit service as per https://www.drupal.org/node/3369935 and used `SMTP_ADDRESS` to mimic our current Silta environment variables. Now worked for me locally.

**Review by maijs — APPROVED** [review]
1. Ran the following commands within the PR branch:
```
lando start
lando drush si 
```
2. Opened https://drupal-project.lndo.site/user/password and entered `admin` as a username.
3. Opened https://mail.lndo.site and there was a password reset email from Drupal.

Works as expected!

**Comment by tormi** [comment]
This setup works with Silta `mailhog` service as well: https://feature-wd-266-mailpit.drupal-project.dev.wdr.io/mailhog/

**Review by maijs — APPROVED** [review]

**Pull request merged**
