### PR TITLE
QAG-44: Simplify the PR template

### PR DESCRIPTION
**Pull request by sampoturve**
## Description

This PR is using the new simpler template 🌿

- Removed 'Best practices' section for being redundant
- Add square brackets for all the texts that should be replaced, to make it clearer on what to update
- This template will still have the `MD041/first-line-heading/first-line-h1: First line in a file should be a top-level heading` linting error, but IMO it doesn't make any sense to add level 1 heading here just for the sake of it.

One thing I'd still consider removing is the `Setting up local environment` section, as I think those steps should be added under `Testing instructions` section, even though the instructions can be used for both local and feature environment testing.

### Feature environment

No feature environment.

### Setting up local environment

No local environment setting up required.

### Testing instructions

See that the PR template makes sense.

### CODE REVIEW

**Comment by tormi** [comment]
What about even simpler approach?

## Ticket GH-406

### Changes

- Simplify Drupal project template pull request template

### Testing

Environment: https://environment.tld

#### Checks

- [ ] check if headings are sized hierarchically
- [ ] check if template follows the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] ...

Markdown:

```md
## Ticket GH-406

### Changes

- Simplify Drupal project template pull request template

### Testing

Environment: https://environment.tld

#### Checks

- [ ] check if headings are sized hierarchically
- [ ] check if template follows the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] ...
```

**Comment by tormi** [comment]
> Adding the ticket link into the title could be an option, but IMO it's way easier to simply copy-paste the URL under a certain heading instead of needing to do some formatting in the way of ## Ticket [GH-385](https://github.com/wunderio/drupal-project/pull/385)

@sampoturve, here we should turn on GH Autolinks, see https://wunder.atlassian.net/browse/QAG-15 for details. After this, link appears automatically.

> I maybe wouldn't go with the checklists
Fair enough.

> Balancing act, this
Let it be.

**Comment by tormi** [comment]
@sampoturve , I changed the 1st section as follows and as you can see it creates the link automatically:

```md
## Ticket QAG-44
```

**Comment by tormi** [comment]
I pushed the changes we discussed in ad900a3. Using [GH Autolinks reference](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources) is really beneficial as it enforces us to reference to the actual and valid ticket while making changes.

**Review by misterjoonas — APPROVED** [review]
Short and nice

**Pull request merged**
