### PR TITLE
Add tooling for dynamically enabled and disabled xdebug

### PR DESCRIPTION
**Pull request by mgalang**
# Feature

This adds a tooling for dynamically enabled and disabling xdebug when needed. 
This also allows xdebug to be toggled without the need for rebuild/restart.

See: https://github.com/lando/lando/issues/1668

### CODE REVIEW

**Comment by tormi** [comment]
Thanks, @mgalang ! 

Maybe we should add some notes to readme as well about the new tools.

Also, what do you think if we should add some default Xdebug `php.ini` settings from here: https://docs.lando.dev/config/php.html#configuration ?

**Comment by tormi** [comment]
@mgalang , @hkirsman - should we use something shorter as tool names, like `lando xon`, `lando xoff`?

**Comment by martin-klima** [comment]
I think we should leave xdebug-on, xdebug-off. The commands should be self-explaining. We also don't have a shortcut for db-import. Anyone can create own shortcuts as system aliases.

**Comment by martin-klima** [comment]
Sorry guys, I thought I'm commenting PR in Lando repository. My mistake. :)

**Comment by tormi** [comment]
> I think we should leave xdebug-on, xdebug-off.

Thanks, @martin-klima for the input! I think it will help us moving forward ;)

**Pull request merged**
