### PR TITLE
Upgrade project to Drupal 10. Resolves #313, #315.

### LINKED ISSUE #313: Upgrade template to Drupal 10
> Drupal.org
> [drupal 10.0.0-beta1](https://www.drupal.org/project/drupal/releases/10.0.0-beta1)
> This is a beta release for the next major version of Drupal. Drupal 10 beta releases are intended for site owners and module or theme authors to test compatibility and upgrade paths for Drupal 10.0. Beta releases are not intended for production. Refer to Preparing your site to upgrade to a newer major version for tools you can use to check the Drupal 10 compatibility of modules, themes, and sites. For more information on 10.0.x development, see [#3118143]. The 10.0.x branch also includes all the latest commits that will be backported to 9.5.x and earlier branches.

https://www.drupal.org/project/drupal/releases/10.0.0-beta1

### PR DESCRIPTION
**Pull request by tormi**
*Changes proposed in this PR:*
- upgrade Drupal to v10,
- remove [Warden](https://www.drupal.org/project/warden) which is no longer maintained,
- remove outdated Composer 1 version check from `scripts/composer/ScriptHandler.php`,
- remove duplicate file references from `phpstan.neon`,
- remove `phpspec/prophecy-phpunit` (see https://www.drupal.org/project/drupal/issues/3261743),
- replace `Webmozart\PathUtil\Path` with `Symfony\Component\Filesystem\Path` in `scripts/composer/ScriptHandler.php`.

*Link to feature environment:*

  https://feature-drupal10.drupal-project.dev.wdr.io
  `ssh www-admin@feature-drupal10-shell.drupal-project -J www-admin@ssh.dev.wdr.io`

### CODE REVIEW

**Comment by tormi** [comment]
Filed an issue in https://github.com/wunderio/code-quality/issues/89 during this PR.

**Comment by tormi** [comment]
Importing reference database dump from db.sql.gz log:

```
2023-01-29T22:41:47.515830226Z Importing reference database dump from db.sql.gz
1.63MiB 0:00:01 [ 979KiB/s] [================================>] 100%                          ] 61% ETA 0:00:00
2023-01-29T22:41:53.893037137Z  [success] Cache rebuild complete.
2023-01-29T22:41:56.878459655Z  [success] Cache rebuild complete.
2023-01-29T22:41:59.560325473Z  [error]  The directory /../config/sync/ does not exist.
2023-01-29T22:41:59.560383944Z  
2023-01-29T22:42:03.390752514Z  [error]   (Currently using Removed core modules You must add the following contributed modules and reload this page.
2023-01-29T22:42:03.391659860Z  * CKEditor [1]
2023-01-29T22:42:03.391708049Z  * RDF [2]
2023-01-29T22:42:03.391726269Z 
2023-01-29T22:42:03.391736230Z These modules are installed on your site but are no longer provided by Core.
2023-01-29T22:42:03.391744438Z For more information read the documentation on deprecated modules. [3]
2023-01-29T22:42:03.391751622Z 
2023-01-29T22:42:03.391762579Z [1] https://www.drupal.org/project/ckeditor
2023-01-29T22:42:03.391771428Z [2] https://www.drupal.org/project/rdf
2023-01-29T22:42:03.391779612Z [3] https://www.drupal.org/node/3223395#s-recommendations-for-deprecated-modules
2023-01-29T22:42:03.391788099Z ) 
2023-01-29T22:42:03.442319180Z 
2023-01-29T22:42:03.460318850Z  // Requirements check reports errors. Do you wish to continue?: yes.           
2023-01-29T22:42:03.460369000Z 
2023-01-29T22:42:05.888214103Z  --------------- ------------- --------------- ------------------------------- 
2023-01-29T22:42:05.888706932Z   Module          Update ID     Type            Description                    
2023-01-29T22:42:05.888766750Z  --------------- ------------- --------------- ------------------------------- 
2023-01-29T22:42:05.888780421Z   user            10000         hook_update_n   10000 - Remove non-existent    
2023-01-29T22:42:05.888789143Z                                                 permissions created by         
2023-01-29T22:42:05.888796623Z                                                 migrations.                    
2023-01-29T22:42:05.888803950Z   block_content   entity_chan   post-update     Clear the entity type cache.   
2023-01-29T22:42:05.888811907Z                   ged_constra                                                  
2023-01-29T22:42:05.888820049Z                   int                                                          
2023-01-29T22:42:05.888829745Z   olivero         add_olivero   post-update     Sets the default               
2023-01-29T22:42:05.888838698Z                   _primary_co                   `base_primary_color` value of  
2023-01-29T22:42:05.888846459Z                   lor                           Olivero's theme settings.      
2023-01-29T22:42:05.888882363Z  --------------- ------------- --------------- ------------------------------- 
2023-01-29T22:42:05.888891526Z 
2023-01-29T22:42:05.889828307Z  // Do you wish to run the specified pending updates?: yes.                     
2023-01-29T22:42:05.890110201Z 
2023-01-29T22:42:05.896991591Z  [notice] Module ckeditor has an entry in the system.schema key/value storage, but is missing from your site. <a href="https://www.drupal.org/node/3137656">More information about this error</a>.
2023-01-29T22:42:05.901117235Z  [notice] Module rdf has an entry in the system.schema key/value storage, but is missing from your site. <a href="https://www.drupal.org/node/3137656">More information about this error</a>.
2023-01-29T22:42:07.742607443Z >  [notice] Update started: user_update_10000
2023-01-29T22:42:07.857544570Z >  [notice] Update completed: user_update_10000
2023-01-29T22:42:09.336087233Z >  [notice] Update started: block_content_post_update_entity_changed_constraint
2023-01-29T22:42:09.343417352Z >  [notice] Update completed: block_content_post_update_entity_changed_constraint
2023-01-29T22:42:09.351063657Z >  [notice] Update started: olivero_post_update_add_olivero_primary_color
2023-01-29T22:42:09.564893727Z >  [notice] Update completed: olivero_post_update_add_olivero_primary_color
2023-01-29T22:42:10.721380985Z  [success] Finished performing updates.
```

**Comment by tormi** [comment]
re: _remove duplicate file references from `phpstan.neon`_ - `php_stan` gave the following error msg which had to be addressed:

```
lando grumphp run                                   
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/8: php_compatibility... ✔
Running task 2/8: check_file_permissions... 
Running task 3/8: php_check_syntax... ✔
Running task 4/8: phpcs... ✔
Running task 5/8: php_stan... ✘
Running task 6/8: yaml_lint... 
Running task 7/8: json_lint... 
Running task 8/8: phpunit... 
Aborted ...

php_stan
========

These files are included multiple times:
- /app/vendor/mglaman/phpstan-drupal/extension.neon
- /app/vendor/phpstan/phpstan-deprecation-rules/rules.neon

It can lead to unexpected results. If you're using phpstan/extension-installer, make sure you have removed corresponding neon files from your project config file.
To skip commit checks, add -n or --no-verify flag to commit command
```

**Comment by tormi** [comment]
Let's add [Updates Log](https://github.com/wunderio/drupal-updates-log) module after the initial Drupal 10 upgrade, see https://github.com/wunderio/drupal-project/issues/333.

**Review by Juhani-moilanen — APPROVED** [review]
Looks good :+1:

**Pull request merged**
