### PR TITLE
Drupal 8.8.0.

### PR DESCRIPTION
**Pull request by tormi**
This PR updates the project template to [Drupal 8.8](https://www.drupal.org/project/drupal/releases/8.8.0). Steps to test out:

1. clone the repo & cd to the project root: `git clone git@github.com:wunderio/drupal-project.git && cd drupal-project`
2. select the feature branch: `git checkout feature/drupal-8.8`
3. perform `lando start`

### CODE REVIEW

**Comment by tormi** [comment]
Seems like `"php": ">=7.0.8",` can be removed, it's defined in core now, `vendor/drupal/core-composer-scaffold/composer.json`.

**Comment by tormi** [comment]
This needs also updating: [The sync directory is defined in $settings and not $config_directories](https://www.drupal.org/node/3018145).

**Comment by aleksijohansson** [comment]
There is something wrong with the changes in this PR. I tested the `master` branch of this project locally and with that I can get to the Drupal installation page. Doing the same test with this branch ends up in this error:
Annotation 2019-12-06 202908

**Comment by tormi** [comment]
@aleksijohansson, switching the branches is not enough to rebuild the project if you have built it with pre-8.8 codebase first. I've added steps to test out to the issue description. Perform `lando destroy -y` and then delete the project folder and then follow the testing steps mentioned above.

**Comment by tormi** [comment]
Your use case was more like _How to upgrade my current project to D8.8`. Let's try to describe that process here as well, thanks for testing out!

**Comment by aleksijohansson** [comment]
@tormi I did not have anything pre-built, but instead started from scratch when testing this. I did exactly what you described now in the PR description for testing.

**Comment by tormi** [comment]
> I tested the master branch of this project locally

What happened to this install?

**Comment by aleksijohansson** [comment]
@tormi I tested that **after** I had first tested this branch.

**Comment by tormi** [comment]
Ok. Try this while you're on feature branch:

1. `rm -rf vendor`
2. `rm composer.lock`
3. `lando composer install`

**Comment by aleksijohansson** [comment]
@tormi I tested again from scratch with:
image
and everything worked out fine. I was able to open the Drupal installation page and do an install without issues.

**Pull request merged**
